# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.BinaryField()),
                ('port', models.SmallIntegerField()),
                ('state', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Machine',
                'db_table': 'tb_machine',
                'managed': True,
                'verbose_name_plural': 'Machine',
            },
        ),
    ]
