# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbmachine',
            options={'managed': True, 'verbose_name': 'Makine', 'verbose_name_plural': 'Makine'},
        ),
        migrations.AlterModelTable(
            name='tbmachine',
            table='machine',
        ),
    ]
