# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20170529_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbmachine',
            options={'managed': True, 'verbose_name': 'machine', 'verbose_name_plural': 'machine'},
        ),
    ]
