# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20170529_0744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TbMachine',
            new_name='Machine',
        ),
    ]
