# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_auto_20170529_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='source.MachineKind'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='source.MachineType'),
        ),
    ]
